import { ErrorBanner } from "../../components/ui/feedback";
import { Icon } from "../../components/ui/icon";
import { cx } from "../../lib/class-names";
import type { AiResult, AiStatus } from "../../lib/types";
import { aiContent, fallbackMessages } from "./ai-content";
import type { AiAction } from "./ai.types";
import styles from "./ai.module.css";

type AssistantMode = AiStatus["mode"] | undefined;

export function AiStatusNotice({
  mode,
  result,
  error,
}: {
  mode: AssistantMode;
  result: AiResult | null;
  error?: string;
}) {
  return (
    <>
      <div className={styles["ai-mode"]}>
        <span className={styles["ai-engine"]}>
          <Icon name="sparkle" size={15} />
          {mode === "local"
            ? "Local planning assistant"
            : mode === "provider"
              ? result
                ? "Generated by Groq"
                : "AI via Groq"
              : "Checking assistant…"}
        </span>
        <span>
          {mode === "local"
            ? result?.fallbackReason
              ? "Local draft after an AI attempt"
              : "Rule-based suggestions · no external service"
            : mode === "provider"
              ? "Sends project/task content to Groq when you generate"
              : ""}
        </span>
      </div>
      <ErrorBanner error={error} />
      {result?.fallbackReason && (
        <p className={styles["ai-notice"]} role="status">
          {fallbackMessages[result.fallbackReason]}
        </p>
      )}
      {result?.mode === "provider" && result.contextLimited && (
        <p className={styles["ai-notice"]}>
          AI used a shortened snapshot of your tasks to stay within the request
          limit.
        </p>
      )}
    </>
  );
}

export function SprintSettings({
  goal,
  capacity,
  onGoalChange,
  onCapacityChange,
}: {
  goal: string;
  capacity: number;
  onGoalChange: (goal: string) => void;
  onCapacityChange: (capacity: number) => void;
}) {
  return (
    <div className={cx(styles["form-grid"], styles["ai-inputs"])}>
      <label className={styles["native-label"]}>
        Sprint goal <span className={styles["muted"]}>(optional)</span>
        <input
          className={styles["native-input"]}
          value={goal}
          onChange={(event) => onGoalChange(event.target.value)}
          placeholder="Ship our first release"
          maxLength={500}
        />
      </label>
      <label className={styles["native-label"]}>
        Task capacity
        <input
          className={styles["native-input"]}
          type="number"
          value={capacity}
          min={1}
          max={30}
          onChange={(event) =>
            onCapacityChange(
              Math.max(1, Math.min(30, Number(event.target.value))),
            )
          }
        />
      </label>
    </div>
  );
}

export function AiStart({
  type,
  title,
  mode,
  onGenerate,
}: {
  type: AiAction;
  title?: string;
  mode: AssistantMode;
  onGenerate: () => void;
}) {
  return (
    <div className={styles["ai-start"]}>
      <span className={styles["ai-orb"]}>
        <Icon name="sparkle" size={30} />
      </span>
      <h3 className={styles["native-h3"]}>{title}</h3>
      <p className={styles["native-p"]}>
        {mode === "local"
          ? "Your local assistant uses task details, due dates, and priorities to organize a practical starting point."
          : "Get a useful first draft from your team's work. Review suggestions and make them your own."}
      </p>
      <button
        className={cx(
          styles["native-button"],
          styles["button"],
          styles["primary"],
        )}
        onClick={onGenerate}
        disabled={!mode}
      >
        <Icon name="sparkle" size={17} />
        {aiContent[type].generateLabel}
      </button>
    </div>
  );
}
